export type CategorySlug =
  | "animals"
  | "flowers-nature"
  | "geometric"
  | "fantasy-space"
  | "ocean-landscapes"
  | "cozy-things";

export type ColoringPage = {
  slug: string;
  title: string;
  short: string;
  description: string;
  image: string;
  sourceFile: string;
  spanishUrl: string;
  category: CategorySlug;
  tags: string[];
};

const page = (
  slug: string,
  title: string,
  short: string,
  description: string,
  sourceFile: string,
  spanishSlug: string,
  category: CategorySlug,
  tags: string[],
): ColoringPage => ({
  slug,
  title,
  short,
  description,
  image: `/coloring-pages/${slug}-coloring-page.webp`,
  sourceFile,
  spanishUrl: `https://dibulisto.site/mandalas/${spanishSlug}/`,
  category,
  tags,
});

export const coloringPages = [
  page(
    "ocean-mandala",
    "Ocean Mandala",
    "Shells and starfish",
    "Shells, coral, waves, and starfish create a breezy medium-detail design inspired by the shore.",
    "mandala-botanico.webp",
    "oceano",
    "ocean-landscapes",
    ["ocean", "shells", "mandala"],
  ),
  page(
    "easy-floral-mandala",
    "Easy Floral Mandala",
    "Large petals and leaves",
    "A simple floral mandala with broad petals, clear leaves, and roomy sections that are easy to color.",
    "mandala-petalos-hojas.webp",
    "floral-facil",
    "flowers-nature",
    ["flowers", "easy", "mandala"],
  ),
  page(
    "circles-and-leaves-mandala",
    "Circles and Leaves Mandala",
    "Soft geometric shapes",
    "Interlocking circles and a light ring of leaves bring geometry and nature together.",
    "mandala-circulos-florales.webp",
    "circulos-y-hojas",
    "geometric",
    ["circles", "leaves", "mandala"],
  ),
  page(
    "easy-lotus-mandala",
    "Easy Lotus Mandala",
    "Two rings of petals",
    "A balanced lotus with wide petals and a clean layout for a calm, approachable coloring session.",
    "mandala-loto-geometrico.webp",
    "loto-facil",
    "flowers-nature",
    ["lotus", "easy", "flowers"],
  ),
  page(
    "botanical-star-mandala",
    "Botanical Star Mandala",
    "Points and leafy details",
    "An eight-point star softened by large leaves and crisp botanical lines.",
    "mandala-estrella-botanica.webp",
    "estrella-botanica",
    "geometric",
    ["star", "botanical", "geometric"],
  ),
  page(
    "sun-and-petals-mandala",
    "Sun and Petals Mandala",
    "Bright radial design",
    "A sunny center surrounded by broad petals and a leafy border in an easy, balanced pattern.",
    "mandala-sol-petalos.webp",
    "sol-floral",
    "flowers-nature",
    ["sun", "petals", "easy"],
  ),
  page(
    "geometric-rose-mandala",
    "Geometric Rose Mandala",
    "Rose and symmetrical leaves",
    "A top-down rose combines open petals with a neat ring of leaves.",
    "mandala-rosa-geometrica.webp",
    "rosa-geometrica",
    "flowers-nature",
    ["rose", "flowers", "geometric"],
  ),
  page(
    "geometric-sunflower-mandala",
    "Geometric Sunflower Mandala",
    "Petals and triangular center",
    "A radial sunflower with generous petals, a geometric center, and simple surrounding leaves.",
    "mandala-girasol-geometrico.webp",
    "girasol-geometrico",
    "flowers-nature",
    ["sunflower", "flowers", "geometric"],
  ),
  page(
    "daisy-mandala",
    "Daisy Mandala",
    "Six radial flowers",
    "Six clean-lined daisies circle a small central star in this cheerful printable.",
    "mandala-margaritas-radiales.webp",
    "margaritas-radiales",
    "flowers-nature",
    ["daisy", "flowers", "easy"],
  ),
  page(
    "flowers-and-leaves-mandala",
    "Flowers and Leaves Mandala",
    "Balanced floral wreath",
    "Rounded flowers and broad leaves form a symmetrical botanical design with medium detail.",
    "mandala-flores-y-hojas.webp",
    "flores-y-hojas",
    "flowers-nature",
    ["flowers", "leaves", "botanical"],
  ),
  page(
    "wildflower-mandala",
    "Wildflower Mandala",
    "Gentle botanical pattern",
    "Simple wildflowers and long leaves create an elegant page with comfortable coloring spaces.",
    "mandala-flores-silvestres.webp",
    "flores-silvestres",
    "flowers-nature",
    ["wildflowers", "leaves", "nature"],
  ),
  page(
    "butterflies-and-flowers-mandala",
    "Butterflies and Flowers Mandala",
    "Symmetrical nature design",
    "Four stylized butterflies alternate with flowers and leaves in a clear, harmonious layout.",
    "mandala-mariposas-florales.webp",
    "mariposas-florales",
    "flowers-nature",
    ["butterflies", "flowers", "nature"],
  ),
  page(
    "layered-floral-mandala",
    "Layered Floral Mandala",
    "Medium-detail petals",
    "A layered floral rosette offers extra detail while keeping every section pleasant to color.",
    "mandala-floral-moderado.webp",
    "floral-moderado",
    "flowers-nature",
    ["flowers", "medium", "mandala"],
  ),
  page(
    "squares-and-leaves-mandala",
    "Squares and Leaves Mandala",
    "Botanical geometry",
    "Soft-cornered squares weave together with leaves for an orderly nature-inspired pattern.",
    "mandala-cuadrados-botanicos.webp",
    "cuadrados-botanicos",
    "geometric",
    ["squares", "leaves", "geometric"],
  ),
  page(
    "floral-cat-mandala",
    "Floral Cat Mandala",
    "Cat with a botanical wreath",
    "An elegant cat face sits among broad petals and leaves in a balanced printable mandala.",
    "mandala-gato-floral.webp",
    "gato-floral",
    "animals",
    ["cat", "flowers", "cute"],
  ),
  page(
    "geometric-cat-mandala",
    "Geometric Cat Mandala",
    "Soft facets and leaves",
    "A cat made from gentle geometric shapes sits inside a symmetrical leafy design.",
    "mandala-gato-geometrico.webp",
    "gato-geometrico",
    "animals",
    ["cat", "geometric", "animals"],
  ),
  page(
    "botanical-elephant-mandala",
    "Botanical Elephant Mandala",
    "Elephant and flowers",
    "An elephant head meets large petals and a botanical wreath in this medium-detail page.",
    "mandala-elefante-botanico.webp",
    "elefante-botanico",
    "animals",
    ["elephant", "flowers", "animals"],
  ),
  page(
    "geometric-owl-mandala",
    "Geometric Owl Mandala",
    "Owl, feathers, and leaves",
    "A front-facing owl with round eyes and broad feathers anchors a botanical rosette.",
    "mandala-buho-geometrico.webp",
    "buho-geometrico",
    "animals",
    ["owl", "geometric", "animals"],
  ),
  page(
    "geometric-butterfly-mandala",
    "Geometric Butterfly Mandala",
    "Wings and leafy wreath",
    "A butterfly with open geometric wings is framed by a simple ring of leaves.",
    "mandala-mariposa-geometrica.webp",
    "mariposa-geometrica",
    "animals",
    ["butterfly", "geometric", "nature"],
  ),
  page(
    "concentric-circles-mandala",
    "Concentric Circles Mandala",
    "Arcs, petals, and leaves",
    "Concentric circles unfold into petals, arcs, and leaves in an orderly easy-to-color design.",
    "mandala-circulos-concentricos.webp",
    "circulos-concentricos",
    "geometric",
    ["circles", "geometric", "easy"],
  ),
  page(
    "botanical-spirals-mandala",
    "Botanical Spirals Mandala",
    "Curves and leaves",
    "Four large spirals alternate with leaves around a central flower.",
    "mandala-espirales-botanicas.webp",
    "espirales-botanicas",
    "geometric",
    ["spirals", "leaves", "geometric"],
  ),
  page(
    "repeating-floral-pattern-mandala",
    "Repeating Floral Pattern Mandala",
    "Rhythmic floral geometry",
    "Petals, rounded diamonds, and leaves repeat in a serene radial pattern.",
    "mandala-patron-floral-repetitivo.webp",
    "patron-floral-repetitivo",
    "geometric",
    ["pattern", "flowers", "geometric"],
  ),
  page(
    "mushroom-forest-mandala",
    "Mushroom Forest Mandala",
    "Mushrooms, ferns, and leaves",
    "Woodland mushrooms sit among ferns and leaves in a natural circular composition.",
    "setas-y-bosque.webp",
    "setas-y-bosque",
    "ocean-landscapes",
    ["mushrooms", "forest", "nature"],
  ),
  page(
    "sun-and-moon-mandala",
    "Sun and Moon Mandala",
    "Celestial symmetry",
    "The sun and moon meet among stars and symmetrical leaves.",
    "sol-y-luna.webp",
    "sol-y-luna",
    "fantasy-space",
    ["sun", "moon", "celestial"],
  ),
  page(
    "capybara-with-flowers",
    "Capybara with Flowers",
    "A calm capybara in bloom",
    "A peaceful capybara rests inside a cheerful wreath of large flowers.",
    "capibara-con-flores.webp",
    "capibara-con-flores",
    "animals",
    ["capybara", "flowers", "cute"],
  ),
  page(
    "lighthouse-and-waves-mandala",
    "Lighthouse and Waves Mandala",
    "Lighthouse, sea, and shore",
    "A lighthouse rises above rolling waves and coastal details in a medium-detail page.",
    "faro-y-olas.webp",
    "faro-y-olas",
    "ocean-landscapes",
    ["lighthouse", "ocean", "coast"],
  ),
  page(
    "books-and-flowers",
    "Books and Flowers",
    "Reading with a floral touch",
    "A stack of books nestles among flowers and leaves for a cozy creative break.",
    "libros-y-flores.webp",
    "libros-y-flores",
    "cozy-things",
    ["books", "flowers", "cozy"],
  ),
  page(
    "planets-and-stars-mandala",
    "Planets and Stars Mandala",
    "A geometric solar system",
    "Planets, orbits, and stars form a clear and symmetrical space scene.",
    "planetas-y-estrellas.webp",
    "planetas-y-estrellas",
    "fantasy-space",
    ["planets", "stars", "space"],
  ),
  page(
    "cactus-and-succulents-mandala",
    "Cactus and Succulents Mandala",
    "A hardy little garden",
    "Cacti and succulents in varied shapes create a geometric desert garden.",
    "cactus-y-suculentas.webp",
    "cactus-y-suculentas",
    "flowers-nature",
    ["cactus", "succulents", "plants"],
  ),
  page(
    "floral-axolotl-mandala",
    "Floral Axolotl Mandala",
    "Axolotl among flowers",
    "A friendly axolotl with soft lines fills the center of a lively botanical wreath.",
    "ajolote-floral.webp",
    "ajolote-floral",
    "animals",
    ["axolotl", "flowers", "cute"],
  ),
  page(
    "floral-coffee-cup",
    "Floral Coffee Cup",
    "Coffee, steam, and flowers",
    "A steaming cup surrounded by large flowers creates a warm modern coloring page.",
    "taza-de-cafe-floral.webp",
    "taza-de-cafe-floral",
    "cozy-things",
    ["coffee", "flowers", "cozy"],
  ),
  page(
    "tree-of-life-mandala",
    "Tree of Life Mandala",
    "Roots and leafy branches",
    "Deep roots and a full crown form a symmetrical tree of life ready to print.",
    "arbol-de-la-vida.webp",
    "arbol-de-la-vida",
    "ocean-landscapes",
    ["tree", "nature", "mandala"],
  ),
  page(
    "seashell-mandala",
    "Seashell Mandala",
    "Shells and ocean shapes",
    "Shells, conches, and sea-inspired details spread across a light radial design.",
    "conchas-marinas.webp",
    "conchas-marinas",
    "ocean-landscapes",
    ["shells", "ocean", "beach"],
  ),
  page(
    "guitar-with-flowers",
    "Guitar with Flowers",
    "Music and botanicals",
    "An acoustic guitar is framed by flowers and leaves in a balanced musical design.",
    "guitarra-con-flores.webp",
    "guitarra-con-flores",
    "cozy-things",
    ["guitar", "music", "flowers"],
  ),
  page(
    "sacred-geometry-mandala",
    "Sacred Geometry Mandala",
    "Circles and a central rosette",
    "Interlocking circles, petals, and hexagonal forms create a precise, peaceful pattern.",
    "geometria-sagrada.webp",
    "geometria-sagrada",
    "geometric",
    ["sacred geometry", "circles", "mandala"],
  ),
  page(
    "fantasy-castle-mandala",
    "Fantasy Castle Mandala",
    "Towers, stars, and vines",
    "A storybook castle rises among stars and clean-lined vines.",
    "castillo-de-fantasia.webp",
    "castillo-de-fantasia",
    "fantasy-space",
    ["castle", "fantasy", "fairytale"],
  ),
  page(
    "hot-air-balloon-mandala",
    "Hot Air Balloon Mandala",
    "Flying through clouds",
    "A decorated hot air balloon floats among clouds inside a circular composition.",
    "globo-aerostatico.webp",
    "globo-aerostatico",
    "fantasy-space",
    ["balloon", "clouds", "travel"],
  ),
  page(
    "bees-and-sunflowers-mandala",
    "Bees and Sunflowers Mandala",
    "Bees among bright blooms",
    "Bees and sunflowers come together in a sunny summer-inspired coloring page.",
    "abejas-y-girasoles.webp",
    "abejas-y-girasoles",
    "flowers-nature",
    ["bees", "sunflowers", "summer"],
  ),
  page(
    "under-the-sea-mandala",
    "Under the Sea Mandala",
    "Fish, coral, and seaweed",
    "A fish swims among coral, seaweed, and bubbles in an open underwater scene.",
    "fondo-marino.webp",
    "fondo-marino",
    "animals",
    ["fish", "ocean", "coral"],
  ),
  page(
    "woodland-cottage-mandala",
    "Woodland Cottage Mandala",
    "Cottage, mushrooms, and ferns",
    "A cozy cottage sits among mushrooms, ferns, and trees inside a natural wreath.",
    "casita-del-bosque.webp",
    "casita-del-bosque",
    "ocean-landscapes",
    ["cottage", "forest", "mushrooms"],
  ),
  page(
    "butterflies-and-lavender",
    "Butterflies and Lavender",
    "Wings and fragrant flowers",
    "Elegant butterflies flutter among lavender sprigs in a balanced botanical design.",
    "mariposas-y-lavanda.webp",
    "mariposas-y-lavanda",
    "flowers-nature",
    ["butterflies", "lavender", "flowers"],
  ),
  page(
    "crystals-and-stars-mandala",
    "Crystals and Stars Mandala",
    "Minerals and night sky",
    "Faceted crystals meet stars and crescent moons in a geometric composition.",
    "cristales-y-estrellas.webp",
    "cristales-y-estrellas",
    "geometric",
    ["crystals", "stars", "magic"],
  ),
  page(
    "japanese-garden-mandala",
    "Japanese Garden Mandala",
    "Bridge, water, and maples",
    "A curved bridge, lantern, and maple leaves form a quiet garden scene.",
    "jardin-japones.webp",
    "jardin-japones",
    "ocean-landscapes",
    ["japanese garden", "bridge", "nature"],
  ),
  page(
    "eastern-dragon-mandala",
    "Eastern Dragon Mandala",
    "Dragon, clouds, and flowers",
    "An eastern dragon winds through clouds and flowers inside a circular frame.",
    "dragon-oriental.webp",
    "dragon-oriental",
    "fantasy-space",
    ["dragon", "fantasy", "clouds"],
  ),
  page(
    "whale-and-ocean-mandala",
    "Whale and Ocean Mandala",
    "Whale among the waves",
    "A calm whale swims between rolling waves, bubbles, and broad sea plants.",
    "ballena-y-oceano.webp",
    "ballena-y-oceano",
    "animals",
    ["whale", "ocean", "animals"],
  ),
  page(
    "bicycle-with-flowers",
    "Bicycle with Flowers",
    "A floral basket ride",
    "A classic bicycle with a flower-filled basket makes a cheerful printable page.",
    "bicicleta-con-flores.webp",
    "bicicleta-con-flores",
    "cozy-things",
    ["bicycle", "flowers", "spring"],
  ),
  page(
    "storybook-houses-mandala",
    "Storybook Houses Mandala",
    "Curved roofs and tiny blooms",
    "Three whimsical houses with curved roofs and flowers create a compact fantasy scene.",
    "casas-de-cuento.webp",
    "casas-de-cuento",
    "fantasy-space",
    ["houses", "fairytale", "fantasy"],
  ),
  page(
    "crescent-moon-with-flowers",
    "Crescent Moon with Flowers",
    "A botanical night sky",
    "A large crescent moon cradles flowers and leaves beneath a simple starry sky.",
    "luna-con-flores.webp",
    "luna-con-flores",
    "fantasy-space",
    ["moon", "flowers", "stars"],
  ),
  page(
    "floral-teapot",
    "Floral Teapot",
    "Tea, steam, and petals",
    "A round teapot sits among flowers and leaves in a warm, inviting composition.",
    "tetera-con-flores.webp",
    "tetera-con-flores",
    "cozy-things",
    ["teapot", "flowers", "cozy"],
  ),
  page(
    "fairy-garden-mandala",
    "Fairy Garden Mandala",
    "Fairy, flowers, and mushrooms",
    "A tiny fairy explores flowers, mushrooms, and an enchanted garden door.",
    "jardin-de-hadas.webp",
    "jardin-de-hadas",
    "fantasy-space",
    ["fairy", "garden", "fantasy"],
  ),
  page(
    "window-with-plants",
    "Window with Plants",
    "An indoor garden nook",
    "An arched window is surrounded by hanging plants and pots in a cozy scene.",
    "ventana-con-plantas.webp",
    "ventana-con-plantas",
    "cozy-things",
    ["plants", "window", "cozy"],
  ),
  page(
    "mountains-and-moon-mandala",
    "Mountains and Moon Mandala",
    "A peaceful night landscape",
    "Mountains, pine trees, and a crescent moon form a serene printable night scene.",
    "montanas-y-luna.webp",
    "montanas-y-luna",
    "ocean-landscapes",
    ["mountains", "moon", "nature"],
  ),
] as const;

export const categories = [
  {
    slug: "animals",
    title: "Animal Coloring Pages",
    short: "Cats, wildlife, and gentle creatures",
    description:
      "Printable animal coloring pages featuring cats, owls, elephants, butterflies, ocean animals, and more.",
    hero: "floral-cat-mandala",
    tip: "Color the main animal first, then choose a contrasting palette for the surrounding pattern so the character stays easy to see.",
  },
  {
    slug: "flowers-nature",
    title: "Flower & Nature Coloring Pages",
    short: "Blooms, leaves, bees, and gardens",
    description:
      "Free flower and nature coloring pages with broad petals, leafy patterns, gardens, and bright seasonal details.",
    hero: "easy-floral-mandala",
    tip: "Try two or three flower colors and repeat them around the page. A smaller palette makes botanical patterns feel balanced.",
  },
  {
    slug: "geometric",
    title: "Geometric Mandala Coloring Pages",
    short: "Circles, spirals, and symmetry",
    description:
      "Printable geometric mandalas built from circles, spirals, stars, and repeating shapes in easy and medium levels.",
    hero: "sacred-geometry-mandala",
    tip: "Pick three or four colors and repeat them across matching shapes to emphasize the symmetry.",
  },
  {
    slug: "fantasy-space",
    title: "Fantasy & Space Coloring Pages",
    short: "Castles, moons, dragons, and stars",
    description:
      "Fantasy coloring pages filled with castles, dragons, fairies, planets, moons, and storybook scenes.",
    hero: "fantasy-castle-mandala",
    tip: "Use deeper colors around the edges and brighter shades for stars, magic, and the main character.",
  },
  {
    slug: "ocean-landscapes",
    title: "Ocean & Landscape Coloring Pages",
    short: "Forests, coastlines, and mountains",
    description:
      "Printable landscape and ocean coloring pages with forests, lighthouses, gardens, mountains, shells, and waves.",
    hero: "lighthouse-and-waves-mandala",
    tip: "Separate the sky, land, and water with distinct color families, then add simple gradients to give the scene depth.",
  },
  {
    slug: "cozy-things",
    title: "Cozy Coloring Pages",
    short: "Books, tea, music, and home",
    description:
      "Cozy printable coloring pages featuring books, tea, coffee, music, bicycles, and plant-filled corners.",
    hero: "books-and-flowers",
    tip: "Choose the color of the main object first, then use softer complementary colors for flowers and decorations.",
  },
] as const;

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}
export function getPage(slug: string) {
  return coloringPages.find((item) => item.slug === slug);
}
export function getPagesByCategory(slug: string) {
  return coloringPages.filter((item) => item.category === slug);
}
export function getRelated(item: ColoringPage) {
  return coloringPages
    .filter(
      (candidate) =>
        candidate.slug !== item.slug &&
        (candidate.category === item.category ||
          candidate.tags.some((tag) => item.tags.includes(tag))),
    )
    .slice(0, 4);
}
